language: go

go:
  - 1.2

install:
  - go get code.google.com/p/go.net/html

script:
  - go test

notifications:
  email:
    recipients:
      - rafael@justo.net.br
    on_success: change
    on_failure: always